spGRANT ALL PRIVILEGES ON webdemo.* TO 'database_user'@'localhost';ring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webdemo?serverTimezone=UTC
    username: modul223
    password: 123

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: create
        connection:
          charSet: UTF-8
    open-in-view: true